### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by przemekkowal** [P0WW0W/less-is-more#2]
Is there a way to change font family? I'd love to use it with San Francisco or Lato. I'd like to have choice. Is there a way to do this? Thanks in advance
@edit I wanted to change font size in the "mail" area, when name, subject and actual message is being displayed. For my eye it's too small. Where do I change it?

**Comment by xander-adkins** [comment]
Hello @przemekkowal. I too though about adjusting the font sizes and types, but ultimately wanted to avoid the complications it may cause in future releases of N1. 

Of course you can freely edit your local installation of the Less is More theme with a basic understanding of CSS. You'll want to include CSS over-rides for the Nylas N1 default fonts in the Less is More style sheets. Target the @font-family and @font-family-heading variables with the font of your choice. As for font-size, I think the easiest method for bumping up the type scale in the "mail" section is just to up all the font scales. You can again target the @font-size-base class, and increase it from the default size which is currently set to 14px. If you'd specifically like to change just the font size in the "mail" section you'll have to do a bit of digging for a more specific class.

Hope this is helpful.
